"""Evaluates the exported Teachable Machine model on the validation and test cards.

Writes reports/teachable_evaluation.md. Run from the repo root:
    python -m src.teachable.evaluate
"""
import time

import pandas as pd
from sklearn.metrics import classification_report, confusion_matrix

from src.core.config import CLAIM_CLASSES, DATA_DIR, ROOT
from src.teachable.predict import TM_MODEL_DIR, predict_card

REPORT_FILE = ROOT / "reports" / "teachable_evaluation.md"


def evaluate_split(split: str, mapping: pd.DataFrame) -> tuple[str, float]:
    cards = mapping[mapping["split"] == split].copy()
    scenarios = pd.read_csv(DATA_DIR / f"claims_{split}.csv").set_index("claim_code")["scenario"]
    start = time.time()
    preds = [predict_card(DATA_DIR / f) for f in cards["image_file"]]
    ms_per_card = (time.time() - start) / len(cards) * 1000
    cards["predicted"] = [p.label for p in preds]
    cards["confidence"] = [p.confidence for p in preds]
    cards["scenario"] = cards["claim_code"].map(scenarios)
    accuracy = (cards["predicted"] == cards["label"]).mean()

    labels = list(CLAIM_CLASSES)
    matrix = pd.DataFrame(confusion_matrix(cards["label"], cards["predicted"], labels=labels),
                          index=[f"actual {c}" for c in labels], columns=labels)
    wrong = cards[cards["predicted"] != cards["label"]]
    text = [
        f"## {split.title()} split ({len(cards)} cards)\n",
        f"Accuracy: **{accuracy:.2%}** · average {ms_per_card:.0f} ms per card\n",
        "```\n" + classification_report(cards["label"], cards["predicted"], labels=labels, digits=3) + "```\n",
        "Confusion matrix (rows = actual class):\n",
        matrix.to_markdown() + "\n",
        "Predicted class by claim scenario:\n",
        pd.crosstab(cards["scenario"], cards["predicted"]).to_markdown() + "\n",
        f"Incorrectly classified cards ({len(wrong)}):\n",
        wrong[["claim_code", "scenario", "label", "predicted", "confidence", "image_file"]]
        .to_markdown(index=False) + "\n",
    ]
    return "\n".join(text), accuracy


def main():
    mapping = pd.read_csv(DATA_DIR / "cards" / "card_mapping.csv")
    sections = []
    for split in ("val", "test"):
        text, accuracy = evaluate_split(split, mapping)
        sections.append(text)
        print(f"{split}: {accuracy:.2%}")
    header = (
        "# Teachable Machine evaluation\n\n"
        f"Generated by `python -m src.teachable.evaluate` from the export in "
        f"`{TM_MODEL_DIR.relative_to(ROOT).as_posix()}/`. Never hand-edited.\n\n"
        "The model never saw these cards: only `data/cards/train/` was uploaded for training.\n"
    )
    REPORT_FILE.write_text(header + "\n" + "\n".join(sections), encoding="utf-8")
    print(f"wrote {REPORT_FILE.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
