"""Evaluates the exported Teachable Machine model on the validation and test cards.

Writes reports/teachable_evaluation.md and model/teachable_<version>/metrics.json
(read by the Reports page). Run from the repo root:
    python -m src.teachable.evaluate
"""
import json
import time

import pandas as pd
from sklearn.metrics import classification_report, confusion_matrix, precision_recall_fscore_support

from src.core.config import CLAIM_CLASSES, DATA_DIR, ROOT
from src.teachable.predict import MODEL_VERSION, TM_MODEL_DIR, predict_card

REPORT_FILE = ROOT / "reports" / "teachable_evaluation.md"


def evaluate_split(split: str, mapping: pd.DataFrame) -> tuple[str, dict]:
    cards = mapping[mapping["split"] == split].copy()
    scenarios = pd.read_csv(DATA_DIR / f"claims_{split}.csv").set_index("claim_code")["scenario"]
    start = time.time()
    preds = [predict_card(DATA_DIR / f) for f in cards["image_file"]]
    ms_per_card = (time.time() - start) / len(cards) * 1000
    cards["predicted"] = [p.label for p in preds]
    cards["confidence"] = [p.confidence for p in preds]
    cards["scenario"] = cards["claim_code"].map(scenarios)
    accuracy = (cards["predicted"] == cards["label"]).mean()

    labels = list(CLAIM_CLASSES)
    cm = confusion_matrix(cards["label"], cards["predicted"], labels=labels)
    matrix = pd.DataFrame(cm, index=[f"actual {c}" for c in labels], columns=labels)
    wrong = cards[cards["predicted"] != cards["label"]]
    text = [
        f"## {split.title()} split ({len(cards)} cards)\n",
        f"Accuracy: **{accuracy:.2%}** · average {ms_per_card:.0f} ms per card\n",
        "```\n" + classification_report(cards["label"], cards["predicted"], labels=labels, digits=3) + "```\n",
        "Confusion matrix (rows = actual class):\n",
        matrix.to_markdown() + "\n",
        "Predicted class by claim scenario:\n",
        pd.crosstab(cards["scenario"], cards["predicted"]).to_markdown() + "\n",
        f"Incorrectly classified cards ({len(wrong)}):\n",
        wrong[["claim_code", "scenario", "label", "predicted", "confidence", "image_file"]]
        .to_markdown(index=False) + "\n",
    ]
    precision, recall, f1, support = precision_recall_fscore_support(
        cards["label"], cards["predicted"], labels=labels, zero_division=0)
    metrics = {
        "accuracy": round(float(accuracy), 4),
        "ms_per_card": round(ms_per_card),
        "classes": labels,
        "confusion_matrix": cm.tolist(),
        "per_class": {c: {"precision": round(float(p), 4), "recall": round(float(r), 4),
                          "f1": round(float(f), 4), "support": int(n)}
                      for c, p, r, f, n in zip(labels, precision, recall, f1, support)},
    }
    return "\n".join(text), metrics


def main():
    mapping = pd.read_csv(DATA_DIR / "cards" / "card_mapping.csv")
    sections, metrics = [], {"version": MODEL_VERSION}
    for split in ("val", "test"):
        text, metrics[split] = evaluate_split(split, mapping)
        sections.append(text)
        print(f"{split}: {metrics[split]['accuracy']:.2%}")
    header = (
        "# Teachable Machine evaluation\n\n"
        f"Generated by `python -m src.teachable.evaluate` from the export in "
        f"`{TM_MODEL_DIR.relative_to(ROOT).as_posix()}/` (model {MODEL_VERSION}). Never hand-edited.\n\n"
        "The model never saw these cards: only `data/cards/train/` was uploaded for training.\n"
    )
    REPORT_FILE.write_text(header + "\n" + "\n".join(sections), encoding="utf-8")
    (TM_MODEL_DIR / "metrics.json").write_text(json.dumps(metrics, indent=2), encoding="utf-8")
    print(f"wrote {REPORT_FILE.relative_to(ROOT)} and {(TM_MODEL_DIR / 'metrics.json').relative_to(ROOT)}")


if __name__ == "__main__":
    main()
